### ISSUE TITLE
bakeini isn't baking authordeps

### ISSUE THREAD

**Issue by harleypig** [kentnl/Dist-Zilla-App-Command-bakeini#1]
According to http://dzil.org/tutorial/prereq.html : 

> Sometimes author prereqs (modules used by Dist::Zilla) are indirectly needed, e.g. via a Pod::Weaver configuration. You can declare them in dist.ini with
>
> ; authordep Pod::Weaver::Plugin::StopWords
> ; authordep Pod::Weaver::Section::Support

bakeini isn't bringing these over from dist.ini.meta.

**Comment by kentfredric** [comment]
This issue can be closed now I believe, fixed in both ExpandINI and bakeini.

If you get bored you can file a similar patch to `DZP:INI::Baked` but that's sufficient for a seperate bug now .  =)
